# In kubernetes, configmaps and secrets can be loaded as volumes.
# Instead of creating N number of environment variables in configmaps & secrets, we can directly load all those in a file & use it.

# configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap-vol
data:
  # app.properties is a file name 
  app.properties: |
    db_url: 192.168.44.54
    db_user: databaseadmin

# secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: my-secret-vol
type: Opaque
data:
# app.conf is a file name
  app.conf: |
    MTkyLjE2MC40NC41NAo=

# pod.yml
apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-configmap-as-volume
spec:
  containers:
    - name: ip-app
      image: varun/ip-app
      ports:
        - containerPort: 80
      volumeMounts:
        - name: secret-vol
          mountPath: /app/volume/secret
          # readOnly: true
        - name: configmap-vol
          mountPath: /app/volume/configmap
          # readOnly: true
  volumes:
    - name: secret-vol
      secret:
        secretName: my-secret-vol
    - name: configmap-vol
      configMap:
        name: my-configmap-vol