# In K8S an empty directory is a special type of volumes that can be used to store temporary data.
# It is represented as "emptyDir" volume in your pod specifications
# If the pod is deleted, the data in the emptyDit is also deleted.

# Note: If we want to share the data between the 2 containers within the same pod, the best solution is using "emptyDir"

# https://chatgpt.com/s/t_6866e21c04a4819195fe5826968098c4

# empty-dit.yml
apiVersion: v1
kind: Pod
metadata:
  name: emptydir-nginx
spec: 
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
      volumeMounts:
        - name: emptydir-vol
          mountPath: /var/log/nginx
    - name: busybox
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "while true; do ls /var/log/nginx;
              cat /var/log/nginx/access.log; sleep 5; done"]
      volumeMounts:
        - name: emptydir-vol
          mountPath: /var/log/nginx
  volumes:
    - name: emptydir-vol
      emptyDir: {}