# Generally all the linux OS follow "base64" encoding pattern
#       $ echo "Harsha" | base 64
#       output: SGFyc2hhCg==
# To decode
#       $ echo "SGFyc2hhCg==" | base64 -d
#       output: Harsha

# $ echo '192.168.44.54' | base64
# output: MTkyLjE2MC40NC41NAo=
# $ echo 'databaseadmin' | base64
# output: ZGF0YWJhc2VhZG1pbg==

# secrets.yml
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data: 
  db_url: MTkyLjE2MC40NC41NAo=
  db_user: ZGF0YWJhc2VhZG1pbg==

# pod-secret.yml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret
spec:
  containers:
    - name: ip-app
      image: varun/ip-app
      ports;
        - containerPort: 8080
      env:
        - name: DB_URL
          valueForm:
            secretKeyRef:
              name: my-secret
              key: db_url
        - name: DB_USER
          valeForm:
            secretKeyRef:
              name: my-secret
              key: db_user